version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  be:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
volumes:
  postgres-data:
    driver: local